# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djhuskyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='party_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_id',
            new_name='id',
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together=set([]),
        ),
    ]
