# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djhuskyapp', '0003_auto_20160402_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='party_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
