# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djhuskyapp', '0006_auto_20160402_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='djhuskyapp.Party'),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together=set([('party', 'track_id')]),
        ),
    ]
