# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djhuskyapp', '0007_auto_20160402_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='played',
            field=models.BooleanField(default=False),
        ),
    ]
